/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_hailong_speex_Speex */

#ifndef _Included_org_hailong_speex_Speex
#define _Included_org_hailong_speex_Speex
#ifdef __cplusplus
extern "C" {
#endif
#undef org_hailong_speex_Speex_MODE_NB
#define org_hailong_speex_Speex_MODE_NB 0L
#undef org_hailong_speex_Speex_MODE_WB
#define org_hailong_speex_Speex_MODE_WB 1L
#undef org_hailong_speex_Speex_MODE_UWB
#define org_hailong_speex_Speex_MODE_UWB 2L
/*
 * Class:     org_hailong_speex_Speex
 * Method:    alloc
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_hailong_speex_Speex_alloc
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_hailong_speex_Speex
 * Method:    dealloc
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_hailong_speex_Speex_dealloc
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_hailong_speex_Speex
 * Method:    frameSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_hailong_speex_Speex_frameSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_hailong_speex_Speex
 * Method:    frameBytes
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_hailong_speex_Speex_frameBytes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_hailong_speex_Speex
 * Method:    samplingRate
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_hailong_speex_Speex_samplingRate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_hailong_speex_Speex
 * Method:    setSamplingRate
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_hailong_speex_Speex_setSamplingRate
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_hailong_speex_Speex
 * Method:    quality
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_hailong_speex_Speex_quality
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_hailong_speex_Speex
 * Method:    setQuality
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_hailong_speex_Speex_setQuality
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_hailong_speex_Speex
 * Method:    bitSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_hailong_speex_Speex_bitSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_hailong_speex_Speex
 * Method:    encode
 * Signature: (J[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_org_hailong_speex_Speex_encode
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     org_hailong_speex_Speex
 * Method:    decode
 * Signature: (J[BI[B)I
 */
JNIEXPORT jint JNICALL Java_org_hailong_speex_Speex_decode
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jbyteArray);

/*
 * Class:     org_hailong_speex_Speex
 * Method:    getHeader
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_org_hailong_speex_Speex_getHeader
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     org_hailong_speex_Speex
 * Method:    allocByHeader
 * Signature: ([BI)J
 */
JNIEXPORT jlong JNICALL Java_org_hailong_speex_Speex_allocByHeader
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     org_hailong_speex_Speex
 * Method:    getMode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_hailong_speex_Speex_getMode
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
